repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
        types_or: [c++, c]
        args: ['--style=file']
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []
